#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/style3lm

PRODUCT_COPY_FILES += \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Codec_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/style3lm/proprietary/vendor/etc/camera/camera_tune_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_tune_config.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/camera/iqm/ai_checker_graph.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/ai_checker_graph.dlc \
    vendor/lge/style3lm/proprietary/vendor/etc/camera/iqm/fc4_awb.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/fc4_awb.dlc \
    vendor/lge/style3lm/proprietary/vendor/etc/camera/iqm/gender_detection_graph.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/gender_detection_graph.dlc \
    vendor/lge/style3lm/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/lge/style3lm/proprietary/vendor/etc/init/android.hardware.nfc@1.2-service-cxd22xx.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.nfc@1.2-service-cxd22xx.rc \
    vendor/lge/style3lm/proprietary/vendor/etc/init/vendor.lge.hardware.powerhint.rescontrol@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.powerhint.rescontrol@2.0-service.rc \
    vendor/lge/style3lm/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_Dual_nt35597_cmd_mode_dsi_truly_panel_without_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt35597_cmd_mode_dsi_truly_panel_without_DSC.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_Dual_nt36850_cmd_mode_dsi_truly_panel_without_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt36850_cmd_mode_dsi_truly_panel_without_DSC.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_SW43410_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_SW43410_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_4k_video_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_4k_video_mode_dsc_dsi_panel.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_hx8399_video_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_hx8399_video_mode_dsi_truly_panel.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/qdcm_calib_data_nt35597_video_mode_dsi_truly_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35597_video_mode_dsi_truly_panel_with_DSC.xml \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/ak991x_dri_0.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/apds9999.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9999.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/etc_version:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/etc_version \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icm4x6xx_0.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sdm845_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_ak991x_0.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sdm845_apds9999_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_apds9999_0.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sdm845_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_icm4x6xx_0.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sdm845_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_power_0.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sensors_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sensors_list.txt \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_disabled.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_enabled.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_basic_gestures.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_bring_to_ear.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_cm.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_device_orient.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_diag_filter.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_distance_bound.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dpc.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_facing.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_fmv.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_geomag_rv.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_gyro_cal.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_lg_filtered_pressure.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_filtered_pressure.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_lg_gated_gyro.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_gated_gyro.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_multishake.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_pedometer.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rmd.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rotv.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_smd.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_disabled.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_enabled.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_to_wake.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/config/sns_window_orientation.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_window_orientation.json \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/registry/sensors_registry:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_registry \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/registry/sensors_settings:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_settings \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/registry/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/sns_reg_config \
    vendor/lge/style3lm/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lge/style3lm/proprietary/vendor/etc/wifi/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.bin \
    vendor/lge/style3lm/proprietary/vendor/etc/wifi/bdwlan_ch0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan_ch0.bin \
    vendor/lge/style3lm/proprietary/vendor/etc/wifi/bdwlan_ch1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan_ch1.bin \
    vendor/lge/style3lm/proprietary/vendor/etc/wifi/icudt53l.dat:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/icudt53l.dat \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUMICRON_MT128GASAO4U21_0107.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUMICRON_MT128GASAO4U21_0107.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUMICRON_MT128GASAO4U21_0108.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUMICRON_MT128GASAO4U21_0108.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSAMSUNG_KLUDG4U1EA-B0C1_0500.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KLUDG4U1EA-B0C1_0500.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSAMSUNG_KLUDG4UHDC-B0E1_0200.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KLUDG4UHDC-B0E1_0200.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSAMSUNG_KLUDG8V1EE-B0C1_0400.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KLUDG8V1EE-B0C1_0400.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSAMSUNG_KLUEG8UHDC-B0E1_0200.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KLUEG8UHDC-B0E1_0200.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSAMSUNG_KM2V8001CM-B707_2100.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KM2V8001CM-B707_2100.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSAMSUNG_KM8V8001JM-B813_2100.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KM8V8001JM-B813_2100.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSKHYNIX_H28S7Q302BMR_A002.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSKHYNIX_H28S7Q302BMR_A002.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSKHYNIX_H28U62301AMR_D003.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSKHYNIX_H28U62301AMR_D003.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSKHYNIX_H28U72301CMR_0004.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSKHYNIX_H28U72301CMR_0004.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUSKHYNIX_H28U74303AMR_D003.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSKHYNIX_H28U74303AMR_D003.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUTOSHIBA_THGAF8G9T43BAIRB_0300.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUTOSHIBA_THGAF8G9T43BAIRB_0300.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUWDC_SDINDDH4-128G_1308.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUWDC_SDINDDH4-128G_1308.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUWDC_SDINDDH4-256G_1308.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUWDC_SDINDDH4-256G_1308.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUWDC_SDINEDK4-128G_1094.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUWDC_SDINEDK4-128G_1094.bin \
    vendor/lge/style3lm/proprietary/vendor/ffu/FFUWDC_SDINEDK4-256G_1088.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUWDC_SDINEDK4-256G_1088.bin \
    vendor/lge/style3lm/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lge/style3lm/proprietary/vendor/firmware/Tfa9872.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9872.cnt \
    vendor/lge/style3lm/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/lge/style3lm/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/lge/style3lm/proprietary/vendor/firmware/cxd225x_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cxd225x_firmware.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.sensormodule.s5kgm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.s5kgm2.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.sensormodule.sl556.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sl556.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.sensormodule.sl846.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sl846.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.default.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.tuned.s5kgm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.s5kgm2.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.tuned.sl556.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.sl556.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/com.qti.tuned.sl846.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.sl846.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin \
    vendor/lge/style3lm/proprietary/vendor/lib/camera/titan17x_usecases.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/titan17x_usecases.bin

PRODUCT_PACKAGES += \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    libc++_shared \
    liblgawb_main \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libsensorcal \
    libsensorslog \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    libssc_default_listener \
    libsymphony-1.1.4 \
    libsymphony-cpu \
    libsymphonypower-1.1.4 \
    libvendor_rescontrol \
    sensors.ssc \
    vendor.lge.hardware.powerhint.rescontrol@2.0-common \
    vendor.lge.hardware.powerhint.rescontrol@2.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    com.qti.sensor.s5kgm2 \
    com.qti.sensor.sl556 \
    com.qti.sensor.sl846 \
    com.lge.node.camerasolution \
    com.lge.node.capturebokeh \
    com.lge.node.elpis \
    com.lge.node.elvis \
    com.lge.node.hdr \
    com.lge.node.lavis \
    com.lge.node.multiframe \
    com.lge.node.realtimebokeh \
    com.lge.node.warp \
    com.lge.stats.aec \
    com.lge.stats.aecwrapper \
    com.lge.stats.af \
    com.lge.stats.af_core \
    com.lge.stats.awb \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    liblg_aec_param_s5kgm2_48M_preview \
    liblg_aec_param_s5kgm2_cine_video \
    liblg_aec_param_s5kgm2_hfr_120 \
    liblg_aec_param_s5kgm2_hfr_240 \
    liblg_aec_param_s5kgm2_hfr_480 \
    liblg_aec_param_s5kgm2_hfr_60 \
    liblg_aec_param_s5kgm2_night_preview \
    liblg_aec_param_s5kgm2_out_focus \
    liblg_aec_param_s5kgm2_out_focus_video \
    liblg_aec_param_s5kgm2_panorama \
    liblg_aec_param_s5kgm2_preview \
    liblg_aec_param_s5kgm2_sensor_hdr_auto_preview \
    liblg_aec_param_s5kgm2_sensor_hdr_auto_video \
    liblg_aec_param_s5kgm2_sensor_hdr_on_preview \
    liblg_aec_param_s5kgm2_sensor_hdr_on_video \
    liblg_aec_param_s5kgm2_steady_cam \
    liblg_aec_param_s5kgm2_video \
    liblg_aec_param_sl556_cine_video \
    liblg_aec_param_sl556_hfr_120 \
    liblg_aec_param_sl556_hfr_240 \
    liblg_aec_param_sl556_hfr_60 \
    liblg_aec_param_sl556_night_preview \
    liblg_aec_param_sl556_out_focus \
    liblg_aec_param_sl556_out_focus_video \
    liblg_aec_param_sl556_panorama \
    liblg_aec_param_sl556_preview \
    liblg_aec_param_sl556_sensor_hdr_auto_preview \
    liblg_aec_param_sl556_sensor_hdr_auto_video \
    liblg_aec_param_sl556_sensor_hdr_on_preview \
    liblg_aec_param_sl556_sensor_hdr_on_video \
    liblg_aec_param_sl556_steady_cam \
    liblg_aec_param_sl556_video \
    liblg_aec_param_sl846_cine_video \
    liblg_aec_param_sl846_out_focus \
    liblg_aec_param_sl846_out_focus_video \
    liblg_aec_param_sl846_preview \
    liblg_aec_param_sl846_sensor_hdr_auto_preview \
    liblg_aec_param_sl846_sensor_hdr_auto_video \
    liblg_aec_param_sl846_sensor_hdr_on_preview \
    liblg_aec_param_sl846_sensor_hdr_on_video \
    liblg_aec_param_sl846_video \
    liblg_awb_param_s5kgm2n_preview \
    liblg_awb_param_s5kgm2n_video \
    liblg_awb_param_sl556w_preview \
    liblg_awb_param_sl556w_video \
    liblg_awb_param_sl846f_preview \
    liblg_awb_param_sl846f_video \
    camera.sdm845 \
    com.qti.chi.override \
    lib.com.lge.elvis \
    libAutoContrast \
    libSJVideoNR \
    libSNPE \
    libSRIyuv \
    libVDRTStereoDepth \
    libVDStereoDepth \
    libarcsoft_beauty_picselfie \
    libarcsoft_picselfie_algorithm \
    libbwfocuspeaking \
    libcamxfdalgov7 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxtintlessalgo \
    libcinemaeffect \
    libcom.qti.chinodeutils \
    libfilm_emulation \
    libfilm_emulation_symphony \
    liblgae_main \
    liblgdnnsnpe \
    liblghdri \
    libmorpho_image_stab31 \
    libmorpho_superzoom \
    libmorpho_wdr2 \
    libmpbase \
    libsymphonypower \
    fingerprint.sdm845 \
    libRbsFlow \
    libets_teeclient_v2 \
    libfpsph \
    libnanopb \
    libsensor_lge_cal \
    libsns_api \
    AlacDecoderModule.so \
    ApeDecoderModule.so \
    AudioContextDetection.so \
    AudioSphereModule.so \
    CFCMModule.so \
    EtsiAmrWbPlusDecModule.so \
    EtsiEaacPlusEncAndCmnModule.so \
    FlacDecoderModule.so \
    HeaacDecoderModule.so \
    LdacModule.so \
    SAPlusCmnModule.so \
    SVACmnModule.so \
    VoiceWakeup_V2_Module.so \
    VorbisDecoderModule.so \
    WmaProDecoderModule.so \
    WmaStdDecoderModule.so \
    fastrpc_shell_0 \
    fluence_voiceplus_module.so \
    libFastRPC_UTF_Forward_skel \
    libVC1Dec \
    libVC1DecDsp_skel \
    libapps_mem_heap \
    libcamera_nn_skel \
    libdspCV_skel \
    libdsp_streamer_add_constant \
    libdsp_streamer_binning \
    libdsp_streamer_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhexagon_nn_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    libstabilitydomain_skel \
    libsysmon_skel \
    libsysmondomain_skel \
    mmecns_module.so \
    chre \
    android.hardware.nfc@1.2-service-cxd22xx \
    vendor.lge.hardware.powerhint.rescontrol@2.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    sensors.qti \
    sscrpcd

PRODUCT_PACKAGES += \
    vendor_firmware_wlan_qca_cld_bdwlan_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch0_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch1_bin
